### PR TITLE
Merge branch 'GitLab/nv-release-1.4.0' into nv-release_1.4.0

### PR DESCRIPTION
**Pull request by NvTimLiu**

### CODE REVIEW

**Comment by wbo4958** [comment]
@NvTimLiu Can we build pass with PR?

**Comment by NvTimLiu** [comment]
> @NvTimLiu Can we build pass with PR?

Building still running

**Comment by NvTimLiu** [comment]
BUILD PASS: 
xgboost_1.4.2-premerge/10/console

**Review by wbo4958 — APPROVED** [review]
LGTM

**Pull request merged**
